[manifest]
id = "mm_recomp_save_editor"
version = "1.1.1"
display_name = "Save Editor"
description =  """
A save editor for Zelda 64: Recompiled with in-game editing for player status, equipment, inventory, quest flags, and dungeon progress."""
short_description = "Edit MM save data in-game."
authors = [ "Linkzenic" ]
game_id = "mm"
minimum_recomp_version = "1.2.2"
dependencies = []
optional_dependencies = []
native_libraries = []

config_options = [
    { id = "editor_hotkey", name = "Editor Hotkey", description = "Button combo used to open the in-game editor.", type = "Enum", options = [ "L + C-Up", "L + D-Up", "L + R + D-Up", "L + R", "Disabled" ], default = "L + C-Up" },
]

[inputs]
elf_path = "build/mod.elf"
mod_filename = "mm_recomp_save_editor"
func_reference_syms_file = "Zelda64RecompSyms/mm.us.rev1.syms.toml"
data_reference_syms_files = [ "Zelda64RecompSyms/mm.us.rev1.datasyms.toml", "Zelda64RecompSyms/mm.us.rev1.datasyms_static.toml" ]
additional_files = [ "thumb.png" ]
